### ISSUE TITLE
I am unable to Resize the Plasmoid.

### ISSUE THREAD

**Issue by PraddyumnYadav** [DenysMb/ChatQTP-Plasmoid#10]
The Default Size of the Plasmoid is too small for me so I try to Resize it from a Corner but whenever my Cursor goes near that I doesn't Give me the Resize Cursor Icon.

**Comment by DenysMBarbosa** [comment]
I'll try to give a better way to resize, but you can do it by holding Meta + Right Mouse Button.

![Peek 2023-07-25 18-17](https://github.com/DenysMb/ChatQTP-Plasmoid/assets/119663902/824ebf35-98bf-4009-8126-54c3715d7f0f)

**Comment by DenysMb** [comment]
I'll try to give a better way to resize, but you can do it by holding Meta + Right Mouse Button.

![Peek 2023-07-25 18-17](https://github.com/DenysMb/ChatQTP-Plasmoid/assets/33737137/91faa5e5-b9bc-4df5-a2c7-627b9d857756)

**Comment by PraddyumnYadav** [comment]
Thank You @DenysMb for your Time and this Project.
